name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  smoke:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Init DB
        run: python -m src init-db --db data/fcc_tm.sqlite

      - name: Generate sample data
        run: python -m src generate --db data/fcc_tm.sqlite --n-customers 50 --n-externals 30 --n-accounts 60 --n-transactions 1000 --seed 7

      - name: Upload sample DB (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sample-db-${{ matrix.os }}
          path: data/fcc_tm.sqlite